# Generated by `mix grpc.gen`.
# DO NOT EDIT!
defmodule Postnord.GRPC do
  @external_resource Path.expand("../../../priv/protos/postnord.proto", __DIR__)
  use Protobuf, from: Path.expand("../../../priv/protos/postnord.proto", __DIR__)
end

defmodule Postnord.GRPC.Node.Service do
  use GRPC.Service, name: "postnord.Node"

  rpc :Write, Postnord.GRPC.WriteRequest, Postnord.GRPC.WriteReply
  rpc :Read, Postnord.GRPC.ReadRequest, Postnord.GRPC.ReadReply
  rpc :Confirm, Postnord.GRPC.ConfirmRequest, Postnord.GRPC.ConfirmReply
  rpc :Replicate, Postnord.GRPC.ReplicateRequest, Postnord.GRPC.ReplicateReply
  rpc :AcquireHold, Postnord.GRPC.AcquireHoldRequest, Postnord.GRPC.AcquireHoldReply
  rpc :Tombstone, Postnord.GRPC.TombstoneRequest, Postnord.GRPC.TombstoneReply
end

defmodule Postnord.GRPC.Node.Stub do
  use GRPC.Stub, service: Postnord.GRPC.Node.Service
end
